select * from DEPARTMENT;
select DEPTCD,DEPTNAME from DEPARTMENT;
select * from EMPLOYEE where GENDERCD = 2 order by BIRTHDAY asc;
select EMPNO,HIREDATE,DEPTCD from ASSIGNMENT where DEPTCD = '07' order by HIREDATE asc;
select PREFCD,PREFNAME,REGION from PREFECTURE where PREFNAME like '%府';
select PREFCD,PREFNAME,REGION from PREFECTURE where PREFNAME like '%島%';
select PREFCD,PREFNAME,REGION from PREFECTURE where PREFNAME like '%川%' or REGION = '四国地方';
select PREFCD,PREFNAME,REGION from PREFECTURE where PREFNAME like '%山%' and REGION = '中部地方';
select EMPNO,EMPNAME from EMPLOYEE where EMPNO in (1100718,1401023,2101799,2201840);
select EMPNO,EMPNAME,BIRTHPLACE from EMPLOYEE where BIRTHPLACE is null;
select EMPNO,DEPTCD,SALARY from ASSIGNMENT where SALARY between 300000 and 400000;

select ASSIGNMENT.EMPNO,EMPLOYEE.EMPNAME,ASSIGNMENT.DEPTCD,ASSIGNMENT.SALARY
from ASSIGNMENT
inner join EMPLOYEE on ASSIGNMENT.EMPNO = EMPLOYEE.EMPNO where ASSIGNMENT.SALARY between 300000 and 400000;

select ASSIGNMENT.EMPNO,EMPLOYEE.EMPNAME,ASSIGNMENT.DEPTCD
from ASSIGNMENT
inner join EMPLOYEE on ASSIGNMENT.EMPNO  = EMPLOYEE.EMPNO where ASSIGNMENT.DEPTCD = 06;

select ASSIGNMENT.EMPNO,EMPLOYEE.EMPNAME,ASSIGNMENT.DEPTCD,DEPARTMENT.DEPTNAME
from ASSIGNMENT
inner join EMPLOYEE on ASSIGNMENT.EMPNO  = EMPLOYEE.EMPNO
right join DEPARTMENT on ASSIGNMENT.DEPTCD = DEPARTMENT.DEPTCD where ASSIGNMENT.DEPTCD = 06;

select count(EMPNO) as counts from LANGSKILL where LANGCD = 01;

select LANGUAGE.LANGNAME ,concat(count(EMPNO),'人') as counts
from LANGSKILL
left join LANGUAGE on LANGSKILL.LANGCD = LANGUAGE.LANGCD group by (LANGNAME) desc;

select * from LANGSKILL
left join LANGUAGE on LANGUAGE.LANGCD = LANGSKILL.LANGCD;

select LANGUAGE.LANGNAME,concat(count(EMPNO),'人') as counts
from LANGSKILL
right join LANGUAGE on LANGSKILL.LANGCD = LANGUAGE.LANGCD group by (LANGNAME)
order by count(EMPNO) desc;

select LANGUAGE.LANGNAME,count(EMPNO)
from LANGSKILL
left outer join LANGUAGE on LANGSKILL.LANGCD = LANGUAGE.LANGCD group by (LANGNAME) desc
having count(EMPNO) >=2 ;

select distinct LANGUAGE.LANGNAME from LANGUAGE
left join LANGSKILL on LANGUAGE.LANGCD = LANGSKILL.LANGCD order by LANGNAME desc;

-- 問題24　LANGCDがついていれば全員外国語を話せるのだが…
select  LANGSKILL.EMPNO,EMPLOYEE.EMPNAME,LANGUAGE.LANGNAME,LANGUAGE.LANGCD from LANGUAGE
right join LANGSKILL on LANGUAGE.LANGCD = LANGSKILL.LANGCD
left join EMPLOYEE on LANGSKILL.EMPNO = EMPLOYEE.EMPNO order by LANGNAME desc;

select  EMPLOYEE.EMPNO,EMPLOYEE.EMPNAME,concat(count(LANGUAGE.LANGCD),'ヵ国語') as counts from LANGUAGE
right join LANGSKILL on LANGUAGE.LANGCD = LANGSKILL.LANGCD
right join EMPLOYEE on LANGSKILL.EMPNO = EMPLOYEE.EMPNO group by EMPLOYEE.EMPNAME
having count(LANGUAGE.LANGCD) >=1;


-- 問題26未解決
select distinct EMPLOYEE.EMPNO,GENDER.GENDERNAME from GENDER
inner join EMPLOYEE on GENDER.GENDERCD = EMPLOYEE.GENDERCD
left join LANGSKILL on EMPLOYEE.EMPNO = LANGSKILL.EMPNO
where LANGSKILL.LANGCD is not null;
-- group by GENDER.GENDERCD

select EMPLOYEE.EMPNO,EMPLOYEE.EMPNAME,EMPLOYEE.GENDERCD,PREFECTURE.PREFNAME
from EMPLOYEE
left join PREFECTURE on PREFECTURE.PREFCD = EMPLOYEE.BIRTHPLACE
where EMPLOYEE.GENDERCD = 2;

delete from PREFECTURE where PREFCD = 99 ;
INSERT INTO PREFECTURE VALUES ('99', '海外', '海外');

delete from EMPLOYEE where EMPNAME = '杉並モハマド';
INSERT INTO EMPLOYEE VALUES ('1100718', '杉並モハマド', '1', '1985-08-17', '99');

delete from EMPLOYEE where EMPNAME = '港アリス';
INSERT INTO EMPLOYEE VALUES ('2101799', '港アリス', '2', '1995-12-29', '99');

delete from EMPLOYEE where EMPNAME = '目黒リリー';
INSERT INTO EMPLOYEE VALUES ('2201840', '目黒リリー', '2', '1997-01-18', '99');

select EMPLOYEE.EMPNO,EMPLOYEE.EMPNAME,EMPLOYEE.GENDERCD,PREFECTURE.PREFNAME
from EMPLOYEE
left join PREFECTURE on PREFECTURE.PREFCD = EMPLOYEE.BIRTHPLACE
where EMPLOYEE.GENDERCD = 2;

select PREFECTURE.PREFCD,PREFECTURE.PREFNAME,count(PREFECTURE.PREFNAME) as COUNTS
from EMPLOYEE
left join PREFECTURE
on PREFECTURE.PREFCD = EMPLOYEE.BIRTHPLACE
group by PREFECTURE.PREFNAME
having count(PREFECTURE.PREFNAME) >=2;

select PREFECTURE.REGION,concat(count(PREFECTURE.REGION),'人') as counts from PREFECTURE
left join EMPLOYEE on PREFECTURE.PREFCD = EMPLOYEE.BIRTHPLACE group by PREFECTURE.REGION;

select EMPLOYEE.EMPNO,EMPLOYEE.EMPNAME,count(PREFECTURE.PREFNAME) as count from PREFECTURE
right join EMPLOYEE on PREFECTURE.PREFCD = EMPLOYEE.BIRTHPLACE group by PREFECTURE.PREFNAME;

-- 問題31　group by PREFNAME、countで県ごとの人数を出して、MAXで最大数の人数の県とEMPNAME,EMPNOを抽出したい…
-- select EMPLOYEE.EMPNO,EMPLOYEE.EMPNAME,PREFECTURE.PREFNAME,MAX(count(distinct PREFECTURE.PREFNAME))
-- from EMPLOYEE
-- left join PREFECTURE on PREFECTURE.PREFCD = EMPLOYEE.BIRTHPLACE
-- where MAX(count(distinct PREFECTURE.PREFNAME));

select EMPLOYEE.EMPNO,EMPLOYEE.EMPNAME,PREFECTURE.PREFNAME,EMPLOYEE.BIRTHDAY
from EMPLOYEE
left join PREFECTURE on PREFECTURE.PREFCD = EMPLOYEE.BIRTHPLACE
where DATEDIFF(CURRENT_DATE(),EMPLOYEE.BIRTHDAY)/360 >=40;

select EMPLOYEE.EMPNO,EMPLOYEE.EMPNAME,PREFECTURE.PREFNAME,EMPLOYEE.BIRTHDAY
from EMPLOYEE
left join PREFECTURE on PREFECTURE.PREFCD = EMPLOYEE.BIRTHPLACE
where last_day(EMPLOYEE.BIRTHDAY) = EMPLOYEE.BIRTHDAY;

select EMPLOYEE.EMPNO,EMPLOYEE.EMPNAME,PREFECTURE.PREFNAME,EMPLOYEE.BIRTHDAY
from EMPLOYEE
left join PREFECTURE on PREFECTURE.PREFCD = EMPLOYEE.BIRTHPLACE
where date_format(EMPLOYEE.BIRTHDAY,'%d') = 1;

select EMPLOYEE.EMPNO,EMPLOYEE.EMPNAME,date_format(EMPLOYEE.BIRTHDAY,'%y-%c-%d') as BIRTHDAY from EMPLOYEE
where date_format(EMPLOYEE.BIRTHDAY,'%c-%d') in
(select date_format(EMPLOYEE.BIRTHDAY,'%c-%d')
from EMPLOYEE
group by date_format(EMPLOYEE.BIRTHDAY,'%c-%d')
having count(*) > 1);

select EMPNO,EMPNAME from EMPLOYEE
where substr(EMPNAME,2,1) in
  (
  select substr(EMPNAME,2,1) from EMPLOYEE group by substr(EMPNAME,2,1)
  having count(*) >= 2
);

delete from DEPARTMENT  where DEPTCD =  01;
INSERT INTO DEPARTMENT VALUES ('01', '人事部', '0299801');

delete from DEPARTMENT  where DEPTCD =  02;
INSERT INTO DEPARTMENT VALUES ('02', '総務部', '0399902');

delete from DEPARTMENT  where DEPTCD =  04;
INSERT INTO DEPARTMENT VALUES ('04', '営業部', '1000620');

delete from DEPARTMENT  where DEPTCD =  05;
INSERT INTO DEPARTMENT VALUES ('05', '購買部', '1000612');

delete from DEPARTMENT  where DEPTCD =  06;
INSERT INTO DEPARTMENT VALUES ('06', '研究部', '0700318');

delete from DEPARTMENT  where DEPTCD =  07;
INSERT INTO DEPARTMENT VALUES ('07', '開発部', '1100718');

delete from DEPARTMENT  where DEPTCD =  08;
INSERT INTO DEPARTMENT VALUES ('08', '製造', '1501171');

select DEPARTMENT.DEPTCD,DEPARTMENT.DEPTNAME,EMPLOYEE.EMPNO
from DEPARTMENT
left join EMPLOYEE on DEPARTMENT.EMPNO = EMPLOYEE.EMPNO;

select
EMPLOYEE.EMPNO,
EMPLOYEE.EMPNAME,
DEPARTMENT.DEPTCD,
if(EMPLOYEE.EMPNO = DEPARTMENT.EMPNO, '-', EMPLOYEE.EMPNO) as '部門長EMPNO'
from EMPLOYEE
left join ASSIGNMENT on EMPLOYEE.EMPNO = ASSIGNMENT.EMPNO
left join DEPARTMENT on ASSIGNMENT.DEPTCD = DEPARTMENT.DEPTCD
where EMPLOYEE.GENDERCD = 1;

select
EMPLOYEE.EMPNO,
EMPLOYEE.EMPNAME,
DEPARTMENT.DEPTCD,
if(EMPLOYEE.EMPNO = DEPARTMENT.EMPNO, '-', EMPLOYEE.EMPNAME) as '部門長EMPNO'
from EMPLOYEE
left join ASSIGNMENT on EMPLOYEE.EMPNO = ASSIGNMENT.EMPNO
left join DEPARTMENT on ASSIGNMENT.DEPTCD = DEPARTMENT.DEPTCD
where EMPLOYEE.GENDERCD = 1;

select
E1.EMPNO,
E1.EMPNAME,
ASSIGNMENT.DEPTCD,
case
  when E1.EMPNO = DEPARTMENT.EMPNO
  then '-'
  else E2.EMPNAME
  end as '部門長EMPNO'
from
EMPLOYEE as E1,
EMPLOYEE as E2,
ASSIGNMENT,
DEPARTMENT
where E1.EMPNO = ASSIGNMENT.EMPNO
AND ASSIGNMENT.DEPTCD = DEPARTMENT.DEPTCD
AND E1.GENDERCD = 1
and DEPARTMENT.EMPNO = E2.EMPNO;

select
E1.EMPNO,
E1.EMPNAME,
ASSIGNMENT.DEPTCD,
case
  when E1.EMPNO = DEPARTMENT.EMPNO
  then '〇'
  else '-'
  end as '部門長EMPNO'
from
EMPLOYEE as E1,
EMPLOYEE as E2,
ASSIGNMENT,
DEPARTMENT
where E1.EMPNO = ASSIGNMENT.EMPNO
AND ASSIGNMENT.DEPTCD = DEPARTMENT.DEPTCD
AND E1.GENDERCD = 1
and DEPARTMENT.EMPNO = E2.EMPNO;

select EMPLOYEE.EMPNO,EMPLOYEE.EMPNAME,concat(ASSIGNMENT.SALARY,'円') as '給与'
from EMPLOYEE
left join ASSIGNMENT on EMPLOYEE.EMPNO = ASSIGNMENT.EMPNO
where EMPLOYEE.GENDERCD = 1
order by ASSIGNMENT.SALARY desc;

select concat(sum(ASSIGNMENT.SALARY),'円') as '男性給与合計'
from EMPLOYEE
left join ASSIGNMENT on EMPLOYEE.EMPNO = ASSIGNMENT.EMPNO
where EMPLOYEE.GENDERCD = 1;

select concat(floor(avg(ASSIGNMENT.SALARY)),'円') as '男性給与平均'
from EMPLOYEE
left join ASSIGNMENT on EMPLOYEE.EMPNO = ASSIGNMENT.EMPNO
where EMPLOYEE.GENDERCD = 1;

select 'ここでちょっと一休み' as '';

-- 問題48から50スキップ
-- 問題51　カンマ区切りの方法が不明
select EMPLOYEE.EMPNAME as '社員名',ASSIGNMENT.SALARY as '給与'
from EMPLOYEE
left join ASSIGNMENT on EMPLOYEE.EMPNO = ASSIGNMENT.EMPNO
having ASSIGNMENT.SALARY >
  (select concat(floor(avg(ASSIGNMENT.SALARY)),'円')
  from EMPLOYEE
  left join ASSIGNMENT on EMPLOYEE.EMPNO = ASSIGNMENT.EMPNO
)
order by ASSIGNMENT.SALARY desc;

-- 問題52複数回使用するサブクエリを省略できないか
select EMPLOYEE.EMPNAME as '社員名',concat(ASSIGNMENT.SALARY,'円') as '給与'
from EMPLOYEE
left join ASSIGNMENT on EMPLOYEE.EMPNO = ASSIGNMENT.EMPNO
where ASSIGNMENT.SALARY <
  (select floor(avg(ASSIGNMENT.SALARY))
  from EMPLOYEE
  left join ASSIGNMENT on EMPLOYEE.EMPNO = ASSIGNMENT.EMPNO
)
and ASSIGNMENT.SALARY + 100000 >
(select concat(floor(avg(ASSIGNMENT.SALARY)),'円')
from EMPLOYEE
left join ASSIGNMENT on EMPLOYEE.EMPNO = ASSIGNMENT.EMPNO
)
order by ASSIGNMENT.SALARY desc;

select EMPLOYEE.EMPNO as '社員番号',EMPLOYEE.EMPNAME as '社員名',concat(ASSIGNMENT.SALARY,'円') as '給与'
from EMPLOYEE
left join ASSIGNMENT on EMPLOYEE.EMPNO = ASSIGNMENT.EMPNO
where EMPLOYEE.EMPNO % 2 =1;
